version: "3.8"

services:
  db:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .docker.env
    restart: always

  web:
    build: .
    env_file:
      - .docker.env
    ports:
      - "5000:5000"
    depends_on:
      - db
